/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as BodeRouteImport } from './routes/bode'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as BodeIndexRouteImport } from './routes/bode/index'
import { Route as BodeAffiliateRouteImport } from './routes/bode/affiliate'
import { Route as BodeBanksRouteImport } from './routes/bode/banks'
import { Route as BodeDepositsRouteImport } from './routes/bode/deposits'
import { Route as BodeLoginRouteImport } from './routes/bode/login'
import { Route as BodeNotificationsRouteImport } from './routes/bode/notifications'
import { Route as BodeQrRouteImport } from './routes/bode/qr'
import { Route as BodeReportsRouteImport } from './routes/bode/reports'
import { Route as BodeResultsRouteImport } from './routes/bode/results'
import { Route as BodeSettingsRouteImport } from './routes/bode/settings'
import { Route as BodeSupportRouteImport } from './routes/bode/support'
import { Route as BodeTradeRouteImport } from './routes/bode/trade'
import { Route as BodeUsersRouteImport } from './routes/bode/users'
import { Route as BodeVerifyRouteImport } from './routes/bode/verify'
import { Route as BodeWithdrawalsRouteImport } from './routes/bode/withdrawals'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BodeUsersUserIdRouteImport } from './routes/bode/users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const BodeRoute = BodeRouteImport.update({
  id: '/bode',
  path: '/bode',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const BodeIndexRoute = BodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BodeRoute,
} as any)
const BodeAffiliateRoute = BodeAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => BodeRoute,
} as any)
const BodeBanksRoute = BodeBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => BodeRoute,
} as any)
const BodeDepositsRoute = BodeDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => BodeRoute,
} as any)
const BodeLoginRoute = BodeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BodeRoute,
} as any)
const BodeNotificationsRoute = BodeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BodeRoute,
} as any)
const BodeQrRoute = BodeQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => BodeRoute,
} as any)
const BodeReportsRoute = BodeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BodeRoute,
} as any)
const BodeResultsRoute = BodeResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => BodeRoute,
} as any)
const BodeSettingsRoute = BodeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BodeRoute,
} as any)
const BodeSupportRoute = BodeSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => BodeRoute,
} as any)
const BodeTradeRoute = BodeTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => BodeRoute,
} as any)
const BodeUsersRoute = BodeUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BodeRoute,
} as any)
const BodeVerifyRoute = BodeVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => BodeRoute,
} as any)
const BodeWithdrawalsRoute = BodeWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => BodeRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BodeUsersUserIdRoute = BodeUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => BodeUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/account': typeof AccountRoute
  '/affiliate': typeof AffiliateRoute
  '/bode': typeof BodeRouteWithChildren
  '/deposit': typeof DepositRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/bode/affiliate': typeof BodeAffiliateRoute
  '/bode/banks': typeof BodeBanksRoute
  '/bode/deposits': typeof BodeDepositsRoute
  '/bode/login': typeof BodeLoginRoute
  '/bode/notifications': typeof BodeNotificationsRoute
  '/bode/qr': typeof BodeQrRoute
  '/bode/reports': typeof BodeReportsRoute
  '/bode/results': typeof BodeResultsRoute
  '/bode/settings': typeof BodeSettingsRoute
  '/bode/support': typeof BodeSupportRoute
  '/bode/trade': typeof BodeTradeRoute
  '/bode/users': typeof BodeUsersRouteWithChildren
  '/bode/verify': typeof BodeVerifyRoute
  '/bode/withdrawals': typeof BodeWithdrawalsRoute
  '/bode/': typeof BodeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bode/users/$userId': typeof BodeUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/account': typeof AccountRoute
  '/affiliate': typeof AffiliateRoute
  '/deposit': typeof DepositRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/bode/affiliate': typeof BodeAffiliateRoute
  '/bode/banks': typeof BodeBanksRoute
  '/bode/deposits': typeof BodeDepositsRoute
  '/bode/login': typeof BodeLoginRoute
  '/bode/notifications': typeof BodeNotificationsRoute
  '/bode/qr': typeof BodeQrRoute
  '/bode/reports': typeof BodeReportsRoute
  '/bode/results': typeof BodeResultsRoute
  '/bode/settings': typeof BodeSettingsRoute
  '/bode/support': typeof BodeSupportRoute
  '/bode/trade': typeof BodeTradeRoute
  '/bode/users': typeof BodeUsersRouteWithChildren
  '/bode/verify': typeof BodeVerifyRoute
  '/bode/withdrawals': typeof BodeWithdrawalsRoute
  '/bode': typeof BodeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bode/users/$userId': typeof BodeUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/account': typeof AccountRoute
  '/affiliate': typeof AffiliateRoute
  '/bode': typeof BodeRouteWithChildren
  '/deposit': typeof DepositRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/bode/affiliate': typeof BodeAffiliateRoute
  '/bode/banks': typeof BodeBanksRoute
  '/bode/deposits': typeof BodeDepositsRoute
  '/bode/login': typeof BodeLoginRoute
  '/bode/notifications': typeof BodeNotificationsRoute
  '/bode/qr': typeof BodeQrRoute
  '/bode/reports': typeof BodeReportsRoute
  '/bode/results': typeof BodeResultsRoute
  '/bode/settings': typeof BodeSettingsRoute
  '/bode/support': typeof BodeSupportRoute
  '/bode/trade': typeof BodeTradeRoute
  '/bode/users': typeof BodeUsersRouteWithChildren
  '/bode/verify': typeof BodeVerifyRoute
  '/bode/withdrawals': typeof BodeWithdrawalsRoute
  '/bode/': typeof BodeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bode/users/$userId': typeof BodeUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$code'
    | '/account'
    | '/affiliate'
    | '/bode'
    | '/deposit'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/trade'
    | '/wallet'
    | '/withdraw'
    | '/bode/affiliate'
    | '/bode/banks'
    | '/bode/deposits'
    | '/bode/login'
    | '/bode/notifications'
    | '/bode/qr'
    | '/bode/reports'
    | '/bode/results'
    | '/bode/settings'
    | '/bode/support'
    | '/bode/trade'
    | '/bode/users'
    | '/bode/verify'
    | '/bode/withdrawals'
    | '/bode/'
    | '/api/auth/$'
    | '/bode/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$code'
    | '/account'
    | '/affiliate'
    | '/deposit'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/trade'
    | '/wallet'
    | '/withdraw'
    | '/bode/affiliate'
    | '/bode/banks'
    | '/bode/deposits'
    | '/bode/login'
    | '/bode/notifications'
    | '/bode/qr'
    | '/bode/reports'
    | '/bode/results'
    | '/bode/settings'
    | '/bode/support'
    | '/bode/trade'
    | '/bode/users'
    | '/bode/verify'
    | '/bode/withdrawals'
    | '/bode'
    | '/api/auth/$'
    | '/bode/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/$code'
    | '/account'
    | '/affiliate'
    | '/bode'
    | '/deposit'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/trade'
    | '/wallet'
    | '/withdraw'
    | '/bode/affiliate'
    | '/bode/banks'
    | '/bode/deposits'
    | '/bode/login'
    | '/bode/notifications'
    | '/bode/qr'
    | '/bode/reports'
    | '/bode/results'
    | '/bode/settings'
    | '/bode/support'
    | '/bode/trade'
    | '/bode/users'
    | '/bode/verify'
    | '/bode/withdrawals'
    | '/bode/'
    | '/api/auth/$'
    | '/bode/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  AccountRoute: typeof AccountRoute
  AffiliateRoute: typeof AffiliateRoute
  BodeRoute: typeof BodeRouteWithChildren
  DepositRoute: typeof DepositRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  TradeRoute: typeof TradeRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bode': {
      id: '/bode'
      path: '/bode'
      fullPath: '/bode'
      preLoaderRoute: typeof BodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bode/': {
      id: '/bode/'
      path: '/'
      fullPath: '/bode/'
      preLoaderRoute: typeof BodeIndexRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/affiliate': {
      id: '/bode/affiliate'
      path: '/affiliate'
      fullPath: '/bode/affiliate'
      preLoaderRoute: typeof BodeAffiliateRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/banks': {
      id: '/bode/banks'
      path: '/banks'
      fullPath: '/bode/banks'
      preLoaderRoute: typeof BodeBanksRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/deposits': {
      id: '/bode/deposits'
      path: '/deposits'
      fullPath: '/bode/deposits'
      preLoaderRoute: typeof BodeDepositsRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/login': {
      id: '/bode/login'
      path: '/login'
      fullPath: '/bode/login'
      preLoaderRoute: typeof BodeLoginRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/notifications': {
      id: '/bode/notifications'
      path: '/notifications'
      fullPath: '/bode/notifications'
      preLoaderRoute: typeof BodeNotificationsRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/qr': {
      id: '/bode/qr'
      path: '/qr'
      fullPath: '/bode/qr'
      preLoaderRoute: typeof BodeQrRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/reports': {
      id: '/bode/reports'
      path: '/reports'
      fullPath: '/bode/reports'
      preLoaderRoute: typeof BodeReportsRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/results': {
      id: '/bode/results'
      path: '/results'
      fullPath: '/bode/results'
      preLoaderRoute: typeof BodeResultsRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/settings': {
      id: '/bode/settings'
      path: '/settings'
      fullPath: '/bode/settings'
      preLoaderRoute: typeof BodeSettingsRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/support': {
      id: '/bode/support'
      path: '/support'
      fullPath: '/bode/support'
      preLoaderRoute: typeof BodeSupportRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/trade': {
      id: '/bode/trade'
      path: '/trade'
      fullPath: '/bode/trade'
      preLoaderRoute: typeof BodeTradeRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/users': {
      id: '/bode/users'
      path: '/users'
      fullPath: '/bode/users'
      preLoaderRoute: typeof BodeUsersRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/verify': {
      id: '/bode/verify'
      path: '/verify'
      fullPath: '/bode/verify'
      preLoaderRoute: typeof BodeVerifyRouteImport
      parentRoute: typeof BodeRoute
    }
    '/bode/withdrawals': {
      id: '/bode/withdrawals'
      path: '/withdrawals'
      fullPath: '/bode/withdrawals'
      preLoaderRoute: typeof BodeWithdrawalsRouteImport
      parentRoute: typeof BodeRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bode/users/$userId': {
      id: '/bode/users/$userId'
      path: '/$userId'
      fullPath: '/bode/users/$userId'
      preLoaderRoute: typeof BodeUsersUserIdRouteImport
      parentRoute: typeof BodeUsersRoute
    }
  }
}

interface BodeUsersRouteChildren {
  BodeUsersUserIdRoute: typeof BodeUsersUserIdRoute
}

const BodeUsersRouteChildren: BodeUsersRouteChildren = {
  BodeUsersUserIdRoute: BodeUsersUserIdRoute,
}

const BodeUsersRouteWithChildren = BodeUsersRoute._addFileChildren(
  BodeUsersRouteChildren,
)

interface BodeRouteChildren {
  BodeAffiliateRoute: typeof BodeAffiliateRoute
  BodeBanksRoute: typeof BodeBanksRoute
  BodeDepositsRoute: typeof BodeDepositsRoute
  BodeLoginRoute: typeof BodeLoginRoute
  BodeNotificationsRoute: typeof BodeNotificationsRoute
  BodeQrRoute: typeof BodeQrRoute
  BodeReportsRoute: typeof BodeReportsRoute
  BodeResultsRoute: typeof BodeResultsRoute
  BodeSettingsRoute: typeof BodeSettingsRoute
  BodeSupportRoute: typeof BodeSupportRoute
  BodeTradeRoute: typeof BodeTradeRoute
  BodeUsersRoute: typeof BodeUsersRouteWithChildren
  BodeVerifyRoute: typeof BodeVerifyRoute
  BodeWithdrawalsRoute: typeof BodeWithdrawalsRoute
  BodeIndexRoute: typeof BodeIndexRoute
}

const BodeRouteChildren: BodeRouteChildren = {
  BodeAffiliateRoute: BodeAffiliateRoute,
  BodeBanksRoute: BodeBanksRoute,
  BodeDepositsRoute: BodeDepositsRoute,
  BodeLoginRoute: BodeLoginRoute,
  BodeNotificationsRoute: BodeNotificationsRoute,
  BodeQrRoute: BodeQrRoute,
  BodeReportsRoute: BodeReportsRoute,
  BodeResultsRoute: BodeResultsRoute,
  BodeSettingsRoute: BodeSettingsRoute,
  BodeSupportRoute: BodeSupportRoute,
  BodeTradeRoute: BodeTradeRoute,
  BodeUsersRoute: BodeUsersRouteWithChildren,
  BodeVerifyRoute: BodeVerifyRoute,
  BodeWithdrawalsRoute: BodeWithdrawalsRoute,
  BodeIndexRoute: BodeIndexRoute,
}

const BodeRouteWithChildren = BodeRoute._addFileChildren(BodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  AccountRoute: AccountRoute,
  AffiliateRoute: AffiliateRoute,
  BodeRoute: BodeRouteWithChildren,
  DepositRoute: DepositRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  TradeRoute: TradeRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
